_xrow_bug_reporting_home:
    path:     /ezbugreport
    defaults:
        _controller: BugReportingBundle:Default:index

_xrow_bug_reporting_create:
    path:     /ezbugreport/create/{issue_number}
    defaults: { _controller: BugReportingBundle:Default:create, issue_number: 'none' }
    methods:  [GET, HEAD]

_xrow_bug_reporting_download:
    path:     /ezbugreport/download/{filename}
    defaults: { _controller: BugReportingBundle:Default:download, filename: false }
    methods:  [GET, HEAD]